### ISSUE TITLE
Assets for snake images are missing?

### ISSUE THREAD

**Issue by DMHoodoo** [treboryx/snake-api#1]
Title

**Comment by treboryx** [comment]
Hi there.

GitHub is the place to host your code, not GBs of media files.

**Comment by DMHoodoo** [comment]
Duh, but this is hardly a "snake" API. Just a general purpose media API. Just an odd name for a repository with a misleading readme.

**Comment by treboryx** [comment]
It is also 3 years old and untouched since, but okay!
